language: go
go:
- 1.11.x
go_import_path: github.com/Fantom-foundation/go-lachesis
cache:
  directories:
  - "$HOME/.glide/cache"
  - "$TRAVIS_BUILD_DIR/vendor"
before_install:
- if ! command -v glide; then curl https://glide.sh/get | sh; fi
- go get -v github.com/SamuelMarks/batch-ethkey
- go get -u -d github.com/magefile/mage
- pushd "$GOPATH/src/github.com/magefile/mage" && go run bootstrap.go && popd
- make vendor
addons:
  apt:
    packages:
    - jq
  sonarcloud:
    organization: "fantom-foundation"
script:
  - sonar-scanner
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
jobs:
  allow_failures:
  - script: make test
  include:
  - stage: test
    script: make test
  - stage: testnet
    script: env -i PATH="$PATH" GOPATH="$GOPATH" n=3 logshold='-1,-1,-1,5,0,0' entry='main' BUILD_DIR="$TRAVIS_BUILD_DIR" scripts/multi.bash
notifications:
  slack:
    secure: "WPbL0WD5fY43IGl04bzuglbU1Ll1YIdc+kWvmT+lho3nnZ4YSp8yTT9LLxkOucpZFlNaSWoDY1y6yFD11+OBc6wi3f3h/t8fWl4xMyxiFVsgiRh1lz9MWqVVxEbEdqGlkavIx/q+f6Q/4p9sQvFC9ZiFRPEkCilkZF1zEwygqmb8TS3HZqMbt4wv66pZnljpj+Va3oN5PAx2PYD6FgBxLKimOqC2NWBVyzNcpGkRRk7MayENskuSZ7MB4ctjBc8Vbmk8AMjeBcMfzUwojYL0AizQZhlMCF9C64AQ9oPRF/rGj4XRLM63+E5BtjAv/ZwDuSOUo6QYDhLRKBMxXjzRNETSDtBPTknhJhr6GNuGyONu7oGvZMJaMaZMPbKKwGGC6GzPqf5KY0pY+kBUnhoF8RIKhDP1NTkNl3OVnd3gWXxsMXDqMHS7nvH1ubgMd7D+bDytK2/dSk5XB5ctU6q8z1EAwJ+ckuRsIzOTY+78cTs57pmG3p0ypqeqnui2bDmtD2EQueJ3CrTwnhK3slswjMi0TRsqEGDSrlXH6R4vqqaRj+s4bo0X4CfD6erEpDJxDyN/z7sci8ltXoGs/grZmRdofdFYQPlY1TPJV+zfYQqcXPoVwf4umyYw9FdYDVPC163heTnXlTVCC4rCZdAgQmpxInsNg1TYnfU8bInByCc="
