language: go

go:
  - 1.13.x

go_import_path: github.com/Fantom-foundation/go-lachesis

cache:
  directories:
    - $GOPATH/pkg

env:
  global:
    - GO111MODULE=on

# install: skip

script:
  - go build -v ./...

after_success:
  - |
    if [ -n "$GO_TEST" ]; then
      go test -coverprofile=coverage.txt -covermode=atomic ./...
    elif [ -n "$GO_INTEGRATION_TEST" ]; then
      go test ./integration/
    fi

after_script:
  - |
    if [ -n "$GO_TEST" ]; then
      bash <(curl -s https://codecov.io/bash)
    fi

matrix:
  include:
    - name: go test
      env:
        - GO_TEST=1

    - name: testnet
      env:
        - GO_INTEGRATION_TEST=1
